# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.eu.mailgun.org:587
mail_admin: noreply@mg.gooseashby.com
mail_hostname: mg.gooseashby.com
mail_user: postmaster@mg.gooseashby.com
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml